[package]
name = "clonymccloneface"
version = "0.1.0"
authors = ["Caleb Hattingh <caleb.hattingh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
github-rs = "0.7.0"
serde_json = "1.0"
structopt = { version = "0.3.16", features = [ "paw" ] }
paw = "1.0.0"
cmd_lib = "0.8.3"

[profile.release]
# https://github.com/johnthagen/min-sized-rust
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 'z'